#!/bin/bash
RED='\033[0;31m'
NC='\033[0m'
ORNG='\033[0;33m'
W='\033[1;37m'
ARG=$2                                        # IP addition argument
usage() {                                      # Function: Print a help message.
	echo "Sifter Help Menu"
	echo "*****************"
	echo "+"
	echo "+"
	echo "# sifter		        runs the programs bringing up the menu in a cli environment"
	echo "# sifter    -c      will check the exsiting hosts in the hostlist"
	echo "# sifter    -a '*'  must be added with '' and then automattically appends the hostname/IP to host file"
	echo "# sifter    -e      will open the host file for manual editing"
	echo "# sifter    -m      Opens the Modules Menu"
	echo "# sifter    -b      Runs the Blackwidow Module using the existing host file"
	echo "# sifter    -n      Runs the Nikto Module using the existing host file"
	echo "# sifter    -d      Runs the Dirbuster Module using the existing host file"
	echo "# sifter    -w      Runs the WPScan Module using the existing host file"
	echo "# sifter    -p      Runs the Nmap Module using the existing host file"
	echo "# sifter    -t      Runs theHarvester against target or host file"
	echo "# sifter    -y      Runs the Yuki-Chan Module using the existing host file"
	echo "# sifter	  -o 	  	Runs the Photon module against target or host list"
	echo "# sifter	  -u	  	Checks for any updates on Github"
	echo "# sifter    -h      This Help Menu" 1>&2
}

cd /opt/sifter

while getopts(-o "a:cembndwptoyhu" --long "update,edit,harvest,check,photon,yuki,nmap,wpscan,dirb,help,nikto,widow,add" options; do            	# Loop: Get the next option;
							# use silent error checking;
							# option a takes 1 arguments.
	case "${options}" in

		-c|--check)
			echo -e "${ORNG}"
			figlet -f mini "Checking for live hosts"
			echo -e "${NC}"
			./modules/ping_check.sh
			;;

		-e|--edit)
			echo -e "${ORNG}"
			figlet -f mini "Editing Host List"
			echo -e "${NC}"
			sleep 2
			nano files/host_list.txt
			sleep 2
			./modules/sifter_menu.sh
			;;

		-a|--add)
			echo -e "${ORNG}"
			figlet -f mini "Adding $ARG to host list"
			echo -e "${NC}"
			echo "$ARG" >> files/host_list.txt
			sleep 2
			./modules/sifter_menu.sh
			;;

		m)
			echo -e "${ORNG}"
			figlet -f mini "Module Menu"
			echo -e "${NC}"
			./modules/module_runner.sh
			;;

		-b|--widow)
			echo -e "${ORNG}"
			figlet -f mini "Running BlackWidow"
			echo -e "${NC}"
			./modules/blackwidow_script.sh
			;;

		-n|--nikto)
			echo -e "${ORNG}"
			figlet -f mini "Running Nikto"
			echo -e "${NC}"
			./modules/nikto_script.sh
			;;

		-p|--nmap)
			echo -e "${ORNG}"
			figlet -f mini "Running Nmap"
			echo -e "${NC}"
			./modules/nmap_script.sh
			;;

		-d|--dirb)
			echo -e "${ORNG}"
			figlet -f mini "Running Dirbuster"
			echo -e "${NC}"
			./modules/dirb_script.sh
			;;

		-o|--photon)
			echo -e "${ORNG}"
			figlet -f mini "Running Photon"
			echo -e "${NC}"
			./modules/photon_script.sh
			;;

		-w|--wpscan)
			echo -e "${ORNG}"
			figlet -f mini "Running WPScan"
			echo -e "${NC}"
			./modules/wpscan_script.sh
			;;

		-t|--harvest)
		  echo -e "${ORNG}"
		  figlet -f mini "Running theHarvester"
		  echo -e "${NC}"
		  ./modules/harvester_script.sh
      ;;

 		-y|--yuki)
      echo -e "${ORNG}"
      figlet -f mini "Running Yuki-Chan"
      echo -e "${NC}"
      ./modules/yuki_blackwidow_script.sh
      ;;

    -u|--update)
      echo -e "${ORNG}"
      figlet -f mini "Checking for updates"
      git pull
      echo -e "${W}Done!${NC}"
      ;;

		-h|--help)
			echo -e "${RED}"
			figlet "SifteR"
			echo -e "${NC}"
			usage
			;;

	esac
done
if (( $OPTIND == 1 )); then				# if no option is passed
	./modules/sifter_menu.sh		  	# default command is run
fi
exit 0
