#!/bin/bash
ORNG='\033[0;33m'
NC='\033[0m'
W='\033[1;37m'
LP='\033[1;35m'
YLW='\033[1;33m'
LBBLUE='\e[104m'
RED='\033[0;31m'
ARG=$2                                         # IP addition argument
# Help Menu
usage() {                                      # Function: Print a help message.
	echo "Sifter Help Menu"
	echo "*****************"
	echo "+"
	echo "+"
	echo "# sifter runs the programs bringing up the menu in a cli environment"
	echo "# sifter -c will check the exsiting hosts in the hostlist"
	echo "# sifter -a '*' must be added with '' and then automattically appends the hostname/IP to host file"
	echo "# sifter -e Opens the Exploitation Module"
	echo "# sifter -i Opens the Info-based Module menu"
	echo "# sifter -d Opens the Domain Focused Modules"
	echo "# sifter -n Opens the Network Mapping Modules menu"
	echo "# sifter -w Opens the Website Focused Modules"
	echo "# sifter -wa Opens the Web-App Focused Module menu"
	echo "# sifter -v Opens the Vulnerability Scanning Module Menu"
    echo "# sifter -m Opens the Module Menu directly"
	echo "# sifter -u Checks for any updates on Github"
	echo "# sifter -h This Help Menu" 1>&2
}
# Information Modules
# Enterprise Target Info
cred_mods(){
  cd /opt/sifter
  echo -e "${RED}"
  figlet -f mini "Enterprise Information Gatherers"
  echo -e "${LP}This module focuses on Enterprises and their online presence"
  echo -e "${YLW}eg. web-directories, enterprise email addresses, etc."
  echo -e "${ORNG}"
  PS3='What tool would you like to use?'
          options=("theHarvester" "Osmedeus" "ReconSpider" "Back" "Quit") # "Sunny-Honey \n ssh HoneyPot"
          select opt in "${options[@]}"
          do
                  case $opt in
                            "theHarvester")
                                ./modules/credmods/harvester.sh
                                ;;

                            "Osmedeus")
                                ./modules/credmods/osmedeus.sh
                                ;;

                            "ReconSpider")
                                ./modules/credmods/rspider.sh
                                ;;

                            "Back")
                                modules
                                ;;

                            "Quit")
                                exit 1
                                ;;
                    esac
            done
            echo -e "${NC}"
}
# Individual Target Info
phone_mods(){
  cd /opt/sifter
  echo -e "${RED}"
  figlet -f mini "Targeted Information Gatherers"
  echo -e "${LP}This module focuses on individual targets."
  echo -e "${YLW}eg. Social media information, phone number information, etc."
  echo -e "${ORNG}"
  PS3='What tool would you like to use?'
          options=("Seeker" "Sherlock" "Back" "Quit") # "Sunny-Honey \n ssh HoneyPot"
          select opt in "${options[@]}"
          do
                  case $opt in
                            "Seeker")
                                ./modules/credmods/seeker.sh
                                ;;

                            "Sherlock")
                                ./modules/credmods/sherlock.sh
                                ;;

                            "Back")
                                modules
                                ;;

                            "Quit")
                                exit 1
                                ;;
                    esac
            done
            echo -e "${NC}"
}
# Info Module-Category Selection
info_mods(){
    cd /opt/sifter
    echo -e "${RED}"
    figlet -f mini "Information Gatherers"
    echo -e "${ORNG}"
    PS3='Which module category would you like to use?'
            options=("Enterprise Focus" "Individual Focus" "Back" "Quit") # "Sunny-Honey \n ssh HoneyPot"
            select opt in "${options[@]}"
            do
                    case $opt in
                            "Enterprise Focus")
                                cred_mods
                                ;;

                            "Individual Focus")
                                phone_mods
                                ;;

                            "Back")
                                modules
                                ;;

                            "Quit")
                                exit 1
                                ;;
                    esac
            done
        echo -e "${NC}"

}
# HoneyPot Scanners
honey_mods(){
    cd /opt/sifter
    echo -e "${RED}"
    figlet -f mini "HoneyPot Detection Systems"
    echo -e "${LP}This module focuses on Enterprises and their online presence"
    echo -e "${YLW}eg. web-directories, enterprise email addresses, etc."
    echo -e "${ORNG}"
    PS3='What tool would you like to use?'
            options=("HoneyCaught" "SniffingBear" "Back" "Quit") # "Sunny-Honey \n ssh HoneyPot"
            select opt in "${options[@]}"
            do
                    case $opt in
                            "HoneyCaught")
                                ./modules/honeymods/honeyc.sh
                                ;;

                            "SniffingBear")
                                ./modules/honeymods/s_bear.sh
                                ;;

                            "Back")
                                modules
                                ;;

                            "Quit")
                                exit 1
                                ;;
                    esac
            done
        echo -e "${NC}"

}
# Domain Modules
dom_mods(){
  cd /opt/sifter
  echo -e "${RED}"
  figlet -f mini "Domain Recon Gathering"
  echo -e "${ORNG}"
  PS3='What tool would you like to use?'
          options=("DnsTwist" "Armory" "Omnibus" "Back" "Quit") #"DomainFuzz"
          select opt in "${options[@]}"
          do
                  case $opt in
                            "DnsTwist")
                                ./modules/dommods/dnstwist.sh
                                ;;

#                            "DomainFuzz")
#                                ./modules/dommods/domainfuzz.sh
#                                ;;

                            "Armory")
                                ./modules/dommods/armory.sh
                                ;;

                            "Omnibus")
                                ./modules/dommods/omnibus.sh
                                ;;

                            "Back")
                                modules
                                ;;

                            "Quit")
                                exit 1
                                ;;
                    esac
            done
            echo -e "${NC}"
}
# Network Modules
net_mods(){
  cd /opt/sifter
  echo -e "${RED}"
  figlet -f mini "Network Scanners"
  echo -e "${ORNG}"
  PS3='What tool would you like to use?'
          options=("nMap" "Arp-Scan" "AttackSurfaceMapper" "Armory" "aSnip" "Back"  "Quit")
          select opt in "${options[@]}"
          do
                  case $opt in
                            "nMap")
                                ./modules/netmods/nmap.sh
                                ;;

                            "Arp-Scan")
                                sudo arp-scan -l
                                ;;

                            "AttackSurfaceMapper")
                                ./modules/netmods/asm.sh
                                ;;

                            "aSnip")
                                ./modules/netmods/asnip.sh
                                ;;

                            "Back")
                                modules
                                ;;

                            "Quit")
                                exit 1
                                ;;
                    esac
            done
            echo -e "${NC}"
}
# Vulnerability Scanners
vuln_mods(){
  cd /opt/sifter
  echo -e "${RED}"
  figlet -f mini "Vulnerability Scanners"
  echo -e "${ORNG}"
  PS3='What tool would you like to use?'
          options=("Flan" "RapidScan" "Yuki-Chan" "Back" "Quit")
          select opt in "${options[@]}"
          do
                  case $opt in
                            "Flan")
                                ./modules/vulnscanners/flan.sh
                                ;;

                            "RapidScan")
                                ./modules/vulnscanners/rapidscan.sh
                                ;;

                            "Yuki-Chan")
                                ./modules/vulnscanners/yuki.sh
                                ;;

                            "Back")
                                modules
                                ;;

                            "Quit")
                                exit 1
                                ;;
                    esac
            done
            echo -e "${NC}"
}
# Web-Focused Modules
web_mods(){
  cd /opt/sifter
  echo -e "${RED}"
  figlet -f mini "Website Scanners & Enumerators"
  echo -e "${ORNG}"
  PS3='What tool would you like to use?'
          options=("Konan" "Dirb" "Nikto" "BlackWidow" "WPScan" "Back" "Quit")
          select opt in "${options[@]}"
          do
                  case $opt in
                            "Konan")
                                echo -e "${RED}This module takes 30min+ to run"
                                echo -e "${W}Would you like to continue?(y/n)${NC}"
                                read K_ANS
                                if [[ ${K_ANS} == "y" ]]; then
                                    ./modules/webmods/konan.sh
                                else
                                    web_mods
                                fi
                                ;;

														"Dirb")
																./modules/webmods/dirb.sh
																;;

                            "Nikto")
                                ./modules/webmods/nikto.sh
                                ;;

                            "BlackWidow")
                                ./modules/webmods/widow.sh
                                ;;

                            "WPScan")
                                ./modules/webmods/wpscan.sh
                                ;;

                            "Back")
                                modules
                                ;;

                            "Quit")
                                exit 1
                                ;;
                    esac
            done
            echo -e "${NC}"
}
# Exploitation Modules
ex_mods(){
  cd /opt/sifter
  echo -e "${RED}"
  figlet -f mini "Exploitation Tools"
  echo -e "${ORNG}"
  PS3='What tool would you like to use?'
        options=("MS Specific Tools" "BruteDUM" "TigerShark" "Web Exploiters" "Search for Exploits" "Back" "Quit")
        select opt in "${options[@]}"
        do
                case $opt in
                    "MS Specific Tools")
                        echo -e "${YLW}These tools are used to exploit MicroSoft systems${NC}"
                        echo -e "${W}Would you like to continue?(y/n)${NC}"
                                read M_ANS
                                if [[ ${M_ANS} == 'y' ]]; then
                                    ms_tools
                                else
                                    ex_mods
                                fi
			                    ;;

                    "BruteDUM")
                        bruters
                        ;;

                    "TigerShark")
                        echo -e "${YLW}TigerShark is a multi-tooled phishing framework${NC}"
                                echo -e "${W}Would you like to continue?(y/n)${NC}"
                                read M_ANS
                                if [[ ${M_ANS} == 'y' ]]; then
                                    ./modules/exmods/tiger.sh
                                else
                                    ex_mods
                                fi
                                ;;

                    "Web Exploiters")
                        echo -e "${YLW}These tools are aimed at exploiting websites${NC}"
                                echo -e "${W}Would you like to continue?(y/n)${NC}"
                                read M_ANS
                                if [[ ${M_ANS} == 'y' ]]; then
                                    web_tools
                                else
                                    ex_mods
                                fi
                                ;;

                    "Search for Exploits")
                        echo -e "${YLW}These tools allow you to search to certain exploits or vulnerabilities${NC}"
                                echo -e "${W}Would you like to continue?(y/n)${NC}"
                                read M_ANS
                                if [[ ${M_ANS} == 'y' ]]; then
                                    search_tools
                                else
                                    ex_mods
                                fi
                                ;;

                    "Back")
                        modules
                        ;;

                    "Quit")
                        exit 1
                        ;;

                esac
        done
    echo -e "${NC}"
}
# BruteForce Modules
bruters(){
    cd /opt/sifter
    echo -e "${RED}"
    figlet -f mini "BruteDUM"
    echo -e "${ORNG}"
    echo -e "${YLW}BruteDUM is a bruteforcing tool that consists of Medusa, nCrack, Hydra${NC}"
    echo -e "${W}Would you like to continue?(y/n)${NC}"
    read M_ANS
    if [[ ${M_ANS} == 'y' ]]; then
        ./modules/exmods/brutedum.sh
    else
        ex_mods
	fi
}
# Exploit Searchers
search_tools(){
    cd /opt/sifter
    echo -e "${RED}"
    figlet -f mini "Exploit Finders"
    echo -e "${ORNG}"
    PS3='What tool would you like to use?'
        options=("ShodanSploit" "FindSploit" "Back" "Quit")
        select opt in "${options[@]}"
        do
                case $opt in
                    "ShodanSploit")
                        echo -e "${YLW}ShodanSploit allows for shodan searches to be done in the terminal${NC}"
                        echo -e "${W}Would you like to continue?(y/n)${NC}"
                        read M_ANS
                        if [[ ${M_ANS} == 'y' ]]; then
                            ./modules/exmods/ssploit.sh
                        else
                            ex_mods
			            fi
                        ;;

                    "FindSploit")
                        echo -e "${YLW}This tool allows you to search, copy or compile exploits${NC}"
                        echo -e "${W}Would you like to continue?(y/n)${NC}"
                        read M_ANS
                        if [[ ${M_ANS} == 'y' ]]; then
                            ./modules/exmods/fsploit.sh
                        else
                            ex_mods
			            fi
                        ;;

                    "Back")
                        modules
                        ;;

                    "Quit")
                        exit 1
                        ;;

                esac
        done
    echo -e "${NC}"
}
# MicroSoft Exploitation
ms_tools(){
  cd /opt/sifter
  echo -e "${RED}"
  figlet -f mini "MicroSoft Exploitation Tools"
  echo -e "${ORNG}"
  PS3='What tool would you like to use?'
        options=("ActiveReign" "iSpy" "FuzzyDander" "SMBGhost" "Back" "Quit")
        select opt in "${options[@]}"
        do
                case $opt in
			              "ActiveReign")
			                    echo -e "${YLW}ActiveReign is a LDAP Network-Attack toolkit${NC}"
                                echo -e "${W}Would you like to continue?(y/n)${NC}"
                                read M_ANS
                                if [[ ${M_ANS} == 'y' ]]; then
                                    ./modules/exmods/ar3.sh
                                else
                                    ex_mods
                                fi
			                    ;;

                          "iSpy")
                                echo -e "${YLW}iSpy is a Microsft 'blue' vulnerability scanner${NC}"
                                echo -e "${YLW}Allows exploitation through metasploit${NC}"
                                echo -e "${W}Would you like to continue?(y/n)${NC}"
                                read M_ANS
                                if [[ ${M_ANS} == 'y' ]]; then
                                    ./modules/exmods/ispy.sh
                                else
                                    ex_mods
			                    fi
			                    ;;

                            "FuzzyDander")
 #                               if [[ -f "/opt/sifter/modules/exmods/fuzzydander.sh" ]]; then
                                    echo -e "${LP}FuzzBunch & DanderSpritz Framework,"
                                    echo -e "codename:${RED}FuzzyDander${NC}"
                                    echo -e "${YLW}If you do not know what these tools are or how they work,"
                                    echo -e "you should not be using them. As such no instructions will be added.${NC}"
                                    echo -e "${W}Would you like to continue?(y/n)${NC}"
                                    read M_ANS
                                    if [[ ${M_ANS} == 'y' ]]; then
                                        ./modules/exmods/fuzzydander.sh
                                    else
                                        ex_mods
                                    fi
#                                else
#                                    echo -e "${LBBLUE}This module is not included in the open git repo.${NC}"
#                                    echo -e "${RED}In order to obtain this module, please ensure Sifter is"
#                                    echo -e "completely up-to-date and open an issue requesting it."
#                                    echo -e "Thereafter you may get the module per individual."
#                                    echo -e "${YLW}This is done to prevent script kiddie's from"
#                                    echo -e "causing to much damage.${NC}"
#                                    echo -e "${ORNG}Thank you for understanding. Have a good day.${NC}"
#                                fi
                                ;;

                            "SMBGhost")
                                echo -e "${LP}SMBGhost scans for the CVE-2020-0796 vulnerability in Windows SMB3 protocol${NC}"
                                ./modules/exmods/smbghost.sh
                                ;;

                            "Back")
                                modules
                                ;;

                           "Quit")
                                exit 1
                                ;;
                esac
        done
    echo -e "${NC}"
}
# Web Exploitation
web_tools(){
  cd /opt/sifter
  echo -e "${RED}"
  figlet -f mini "Website Exploitation Tools"
  echo -e "${ORNG}"
  PS3='What tool would you like to use?'
        options=("Dark Star" "NekoBot" "Back" "Quit")
        select opt in "${options[@]}"
        do
                case $opt in
                    "NekoBot")
                        echo -e "${YLW}NekoBot is a Web-Shell exploitation framework${NC}"
                        echo -e "${W}Would you like to continue?(y/n)${NC}"
                        read M_ANS
                        if [[ ${M_ANS} == 'y' ]]; then
                            ./modules/exmods/nekobot.sh
                        else
                            ex_mods
			            fi
                        ;;

                    "Dark Star")
                        echo -e "${YLW}Dark Star is a DDos tool${NC}"
                        echo -e "${W}Would you like to continue?(y/n)${NC}"
                        read M_ANS
                        if [[ ${M_ANS} == 'y' ]]; then
                            ./modules/exmods/dark_star.sh
                        else
                            ex_mods
			            fi
                        ;;

			        "Back")
                        modules
                        ;;

                    "Quit")
                        exit 1
                        ;;
                esac
        done
    echo -e "${NC}"
}
# Web-App Modules
webapps(){
  cd /opt/sifter
  echo -e "${RED}"
  figlet -f mini "WebAppplication Scanners"
  echo -e "${ORNG}"
  PS3='What tool would you like to use?'
        options=("Sitadel" "wafw00f" "BFAC" "AapFinder" "OneFind" "Back" "Quit")
        select opt in "${options[@]}"
        do
                case $opt in
                        "Sitadel")
                            ./modules/webapps/sitadel.sh
                            ;;

                        "wafw00f")
                            ./modules/webapps/wafw00f.sh
                            ;;

                        "AapFinder")
                            ./modules/webapps/aapfinder.sh
                            ;;

                        "BFAC")
                            ./modules/webapps/bfac.sh
                            ;;

                        "OneFind")
                            ./modules/webapps/onefind.sh
                            ;;

                        "Back")
                            modules
                            ;;

                        "Quit")
                            exit 1
                            ;;
                esac
        done
    echo -e "${NC}"
}
# Host Check
check_hosts(){
    echo -e "${RED}NOTE: ${YLW}This will not work if there are no target IP or domains in your host_list.txt file."
    echo -e "${YLW}If you have not added any please go back and select edit host list option"
    echo -e "${W}Would you like to continue?(y/n)${NC}"
    read HOST_ANS
    if [[ ${HOST_ANS} == "y" ]]; then
    	echo -e "${ORNG}Host Check${NC}"
    	echo -e "${ORNG}***********${NC}"
    	rm files/pingtest_raw.pass files/pingtest.pass files/pingtest_pass.txt

    	for name in `cat files/host_list.txt`

    	        do
    	            ping -c 1 $name
    	                if [[ $? == 0 ]]; then
    	                    echo -e "${LP}=================="
    	                    echo -e "\e[95m$name Alive\e[0m" && echo $name >> files/pingtest_raw.pass
    	                    echo -e "${LP}==================${NC}"
    	                else
    	                    echo -e "${RED}=================="
    	                    echo -e "\e[1;31m$name Dead\e[0m" && echo $name >> files/pingtest_raw.fail
    	                    echo -e "${RED}==================${NC}"
    	                fi
    	        done
	
	                sleep 5
	
            echo "============================================================================================================================="

        	echo -e "\e[95mPingtest_Pass\e[0m"
            	echo $'\e[95m*************\e[0m'
		        cat files/pingtest_raw.pass | sort | uniq > files/pingtest.pass
        	    echo -e "${YLW}"
		        cat files/pingtest.pass
		        echo -e "${NC}"
		        sed -e 's/^/http:\/\//' files/pingtest.pass > files/pingtest_pass.txt

        	    echo "============================================================================================================================="

	            echo -e "\e[1;31mPingtest_Fail\e[0m"
	            echo $'\e[1;31m*************\e[0m'
	            cat files/pingtest_raw.fail | sort | uniq > files/pingtest.fail
	            echo -e "${YLW}"
		        cat files/pingtest.fail
		        echo -e "${NC}"
	            sleep 5
        	    menu
     else
		menu
     fi
}
# List Argument Options Settings Below
ip_add() {
  echo -e "${W}Please enter your target:${NC}"
  read IP_ANS
  sleep 1
  echo "$IP_ANS" >> files/host_list.txt
  ip_q
}
ip_q() {
  echo -e "${W}Would you like to add another?(y/n)${NC}"
read ANS
sleep 1
if [[ $ANS == y ]]; then
  ip_add
else
  menu
fi
}
# List Editor
list_editor(){
    echo -e "${RED}List Editor${NC}"
    echo -e "${RED}************${YLW}"
    cat files/host_list.txt
    echo -e "${ORNG}"
            PS3='What would you like to do?'
            options=("Check" "List" "Add" "Remove" "Back")
            select opt in "${options[@]}"
            do
                    case $opt in
                            "Check")
                                check_hosts
                                sleep 5
                                list_editor
                                ;;

                            "Add")
                                if [[ ${TARLIST} == "eg. target.com" ]]; then
                                    rm /opt/sifter/files/host_list.txt
                                    touch /opt/sifter/files/host_list.txt
                                else
                                    sleep 1
                                fi
                                echo -e "${W}Type the IP or hostname you would like to add${NC}"
			                    sleep 5
                                read LTARGET
                                echo "$LTARGET" >> files/host_list.txt
                                echo -e "${W}Target Added!${NC}"
                                ip_q
                                ;;

                            "Remove")
                                nano files/host_list.txt
                                echo -e "${W}Target Removed!${NC}"
                                sleep 5
                                list_editor
                                ;;

                            "Back")
                                menu
                                ;;
                    esac
            done
    echo -e "${NC}"
}
result_choices(){
    echo -e "${ORNG}"
    ls
    echo -e "${NC}"
    PS3='What would you like to do?'
            options=("Check File" "Check Image" "Change Directory" "Back")
            select opt in "${options[@]}"
            do
                    case $opt in
                            "Check File")
                                echo -e "${W}Please enter the file name${NC}"
                                read FNAME
                                if [[ -d '${FNAME}' ]]; then
                                    echo -e "${FNAME} is a directory, please try changing directories instead.${NC}"
                                else
                                    echo -e "${W}==========================================================================${NC}"
                                    cat ${FNAME}
                                    echo -e "${W}==========================================================================${NC}"
                                fi
                                result_choices
                                ;;

                             "Check Image")
                                echo -e "${W}Please enter the image name${NC}"
                                read INAME
                                eom ${INAME}
                                result_choices
                                ;;

                            "Change Directory")
                                echo -e "${W}Please enter the directory name${NC}"
                                read DIR_NAME
                                cd ${DIR_NAME}
                                result_choices
                                ;;

                            "Back")
                                cd /opt/sifter
                                modules
                                ;;

                    esac
            done
    echo -e "${NC}"
}
# Results
results(){
    echo -e "${YLW}Results"
    echo -e "${LP}*******${NC}"
    echo -e "${ORNG}"
    cd /opt/sifter/results
    ls
    echo -e "${W}Please enter the name of the result directory you'd like to see${NC}"
    read DNAME
    cd ${DNAME}
    result_choices
    cd /opt/sifter
}
# Module Menu
modules(){
    echo -e "${RED}Modules${NC}"
    echo -e "${RED}*******${NC}"
    echo -e "${ORNG}"
    PS3='What would you like to do?'
            options=("Information Gatherers" "Domain Recon Gathering" "Network Scanners" "Website Scanners & Enumerators" "Vulnerability Scanners" "HoneyPot Detection Systems" "Exploitation Tools" "WebAppplication Scanners" "View Results" "Main Menu" "Quit")
            select opt in "${options[@]}"
            do
                    case $opt in
                            "Information Gatherers")
                                info_mods
                                ;;

                            "Domain Recon Gathering")
                                dom_mods
                                ;;

                            "Network Scanners")
                                net_mods
                                ;;

                            "Website Scanners & Enumerators")
                                web_mods
                                ;;

                            "Vulnerability Scanners")
                                vuln_mods
                                ;;

                            "HoneyPot Detection Systems")
                                honey_mods
                                ;;

                            "Exploitation Tools")
                                ex_mods
                                ;;

			                "WebAppplication Scanners")
			                    webapps
			                    ;;

                            "View Results")
                                results
                                ;;

                            "Main Menu")
                                menu
                                ;;

                            "Quit")
                                exit 1
                                ;;
                    esac
            done
    echo -e "${NC}"
}
# Menu
menu(){
     if [[ -d "/opt/sifter/results" ]]; then
        sleep 1
    else 
        mkdir /opt/sifter/results
    fi
    echo -e "${ORNG}"
    figlet -f big "'..*SifteR*..'"
    echo -e "${LP}"
    figlet -f small "*s1l3nt78*"
    echo -e "${RED}////////========ChrysalliS_(v4.2)========\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\${NC}"
    echo -e "${W}==Hit Ctrl + c at any time to quit Sifter==${NC}"
    arg=$1
    echo -e "${ORNG}"
    PS3='What would you like to do?'
            options=("Check Hosts" "Edit Host List" "Parse Results to Modules" "Update" "Quit")
            select opt in "${options[@]}"
            do
                case $opt in
                    "Check Hosts")
                        check_hosts
                        ;;

                    "Edit Host List")
                        list_editor
                        ;;

                    "Parse Results to Modules")
                        modules
                        ;;

		            "Update")
		                update
                        ;;

                    "Quit")
                        exit 1
                        ;;
                esac
            done
    echo -e "${NC}"
}
# Update Arg
update(){
    echo -e "${ORNG}"
    figlet -f mini "Checking for updates"
    git fetch
    git pull
    sudo ./install.sh
    sudo cp sifter -t /usr/sbin
    sudo chown $USER:$USER /opt/sifter --recursive
    sudo chown $USER:$USER /usr/sbin/sifter
    chmod +x /opt/sifter --recursive
    chmod +x /usr/sbin/sifter
    echo -e "${W}Done!${NC}"
}

cd /opt/sifter
while getopts "a:wandwirmecvuh" options; do            	# Loop: Get the next option;
	case "${options}" in                                # use silent error checking;
                                                        # option a takes 1 arguments.
		c)
			echo -e "${YLW}"
			figlet -f mini "Checking for live targets..."
			echo -e "${NC}"
			check_hosts
            modules
			;;

		a)
			echo -e "${ORNG}"
			figlet -f mini "Adding $ARG to host list"
			echo -e "${NC}"
            TARLIST=$(cat /opt/sifter/files/host_list.txt)
            if [[ ${TARLIST} == "eg. target.com" ]]; then
                rm /opt/sifter/files/host_list.txt
                touch /opt/sifter/files/host_list.txt
            else
                sleep 1
            fi
			echo "$ARG" >> files/host_list.txt
			sleep 2
			modules
			;;

		i)
			echo -e "${LP}"
			figlet -f mini "Info Gatherers"
			echo -e "${NC}"
			cred_mods
			;;

		d)
			echo -e "${LP}"
			figlet -f mini "Domain-Fuzzers"
			echo -e "${NC}"
			dom_mods
			;;

		e)
			echo -e "${LP}"
			figlet -f mini "Exploitative Modules"
			echo -e "${NC}"
			ex_mods
			;;

		n)
			echo -e "${LP}"
			figlet -f mini "Network Mappers"
			echo -e "${NC}"
			net_mods
			;;

		v)
			echo -e "${LP}"
			figlet -f mini "Vulnerability Scanners"
			echo -e "${NC}"
			vuln_mods
			;;

		wa)
			echo -e "${LP}"
			figlet -f mini "Web-App Testers"
			echo -e "${NC}"
			webapps
			;;

		w)
			echo -e "${LP}"
			figlet -f mini "Web Recon"
			echo -e "${NC}"
			web_mods
			;;

        r)
            echo -e "${LP}"
            figlet -f mini "Sifter Results"
            echo -e "${NC}"
            results
            ;;

        u)
            update
      		;;

		h)
			echo -e "${RED}"
			figlet "SifteR"
			echo -e "${NC}"
			usage
			;;

        m)
            echo -e "${RED}"
            figlet -f mini "Sifter Modules"
            echo -e "${NC}"
            modules
            ;;

	esac
done
if [[ $OPTIND == 1 ]]; then				# if no option is passed
	menu		  	                    # default command is run
fi
exit 0
