#!/bin/bash
RED='\033[0;31m'
NC='\033[0m'
ORNG='\033[0;33m'
W='\033[1;37m'
INV='\e[7m'
URED='\033[4;31m'
UBLUE='\033[4;34m'

echo -e "${RED}"
figlet SifteR
echo -e "${NC}"
sudo docker start sifter
echo -e "${YLW}To detach from docker container ${RED}hold Ctrl and ${W}press P + Q${NC}"
sudo docker attach sifter
echo -e "${ORNG}"
figlet -f mini "Stopping SifteR"
echo -e "${NC}"